### ISSUE TITLE
if ($model->wasChanged()) { return false on created

### ISSUE THREAD

**Issue by ronnievisser** [alexstewartja/laravel-attribute-observer#2] opened 2021-11-24 14:19 UTC
When listening for created events, which is possible according to the documentation, the check $model->wasChanged() returns false. It should be replaced with $model->isDirty();

**Comment by alexstewartja** [comment] 2021-11-25 22:02
@ronnievisser Good first issue! I'll review and proceed accordingly, later this evening.

_PS: When proposing changes, it's recommended to fork the original repo, commit to your fork and submit a pull request_

**Comment by alexstewartja** [comment] 2021-12-02 14:42
@ronnievisser Both `wasChanged()` and `isDirty()` essentially perform the same checks. 

Additionally, I was not able to reproduce your issue. Kindly provide some context (code sample(s) would work beautifully), so I may be better able to understand your use case and specific problem.

**Comment by alexstewartja** [comment] 2021-12-05 15:57
@ronnievisser Closing this, as it's a non-issue.

**Closed as completed by alexstewartja** 2021-12-05 15:57 UTC
Labels: question
